version: '3'
services:
    database:
        image: postgres:11.5
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: db
        networks:
            - app-network
        volumes:
            - ./services/database/data:/data/
            # All SQL files in /docker-entrypoint-initdb.d will be automatically
            # executed in alphabetical order by Postgres upon initialization.
            - ./services/database/migrations:/docker-entrypoint-initdb.d/

    graphql:
        image: node:12
        environment:
            DB_HOST: postgres://user:pass@database:5432/db
        restart: unless-stopped
        links:
            - database
        volumes:
            - ./services/graphql:/graphql
        working_dir: /graphql/
        networks:
            - app-network
        depends_on:
            - database
        command: "npx postgraphile -c postgres://user:pass@database:5432/db --watch --host \"0.0.0.0\""
        ports:
            - 5000:5000

networks:
  app-network:
    driver: bridge 